apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- controller_cluster_role.yaml
- controller_service_account.yaml
- controller_role_binding.yaml
images:
- name: DUMMYSITE_IMAGE
  newName: jamesho287/dummysite
  newTag: v0.2
- name: DUMMYSITE_CONTROLLER_IMAGE
  newName: jamesho287/dummysite_controller
  newTag: v0.1
